export default {
  site: '/setting',
  category: '/category',
  superManager: '/manager/super',
  loginManager: '/manager/login',
  manager: '/manager',
  logoutManager: '/manager/logout',
  memberList: '/member/list',
  member: '/member',
  managerList: '/manager/list',
  postList: '/post/list',
  post: '/post',
  postState: '/post_state',
  postAttachment: '/post/attachment',
  gift: '/gift',
  giftCategory: '/gift_category',
  giftList: '/gift/list',
  giftOrderList: '/gift_order/list',
  giftOrder: '/gift_order',
  noticeInsert: '/notice/insert',
  notice: '/notice',
  noticeList: '/notice/list',
  noticeAttachment: '/notice/attachment'
}
